const assert = require('assert')
const fs = require('fs')

const appConfig = JSON.parse(fs.readFileSync('app.json', 'utf8'))
const friendsPage = fs.readFileSync('pages/friends/friends.js', 'utf8')
const detailPage = fs.readFileSync('pages/recipe-detail/recipe-detail.js', 'utf8')
const recipeListPage = fs.readFileSync('pages/recipe-list/recipe-list.js', 'utf8')
const friendRecipesPage = fs.readFileSync('pages/friend-recipes/friend-recipes.js', 'utf8')
const friendRecipesView = fs.readFileSync('pages/friend-recipes/friend-recipes.wxml', 'utf8')

assert(appConfig.pages.includes('pages/friend-recipes/friend-recipes'))
assert(friendsPage.includes('/pages/friend-recipes/friend-recipes?friendId='))
assert(!friendsPage.includes("wx.setStorageSync('recipeListCreatorFilter'"))
assert(detailPage.includes('/pages/friend-recipes/friend-recipes?friendId='))
assert(!detailPage.includes("wx.setStorageSync('recipeListCreatorFilter'"))
assert(!detailPage.includes('viewCreatorRecipes() {\n    if (this.data.readOnly) return'))
assert(friendRecipesView.includes('show-cart-action="{{false}}"'))
assert(fs.readFileSync('pages/recipe-detail/recipe-detail.wxml', 'utf8').includes('<view class="creator-action" bindtap="viewCreatorRecipes">'))
assert(recipeListPage.includes("wx.removeStorageSync('recipeListCreatorFilter')"))
assert(!recipeListPage.includes('this.setData({ creatorId })'))
assert(friendRecipesPage.includes("action: 'list'"))
assert(friendRecipesPage.includes('creatorId: this.data.friendId'))
assert(friendRecipesPage.includes('&readonly=1'))

console.log('friend recipes: pass')
