const assert = require('assert')
const fs = require('fs')

const friendSource = fs.readFileSync('cloudfunctions/friend/index.js', 'utf8')
const friendConfig = JSON.parse(fs.readFileSync('cloudfunctions/friend/config.json', 'utf8'))
const notificationSource = fs.readFileSync('cloudfunctions/notification/index.js', 'utf8')
const popupSource = fs.readFileSync('components/global-notification-popup/global-notification-popup.js', 'utf8')
const profileSource = fs.readFileSync('pages/profile/profile.js', 'utf8')
const profileView = fs.readFileSync('pages/profile/profile.wxml', 'utf8')
const friendsView = fs.readFileSync('pages/friends/friends.wxml', 'utf8')
const requestPageSource = fs.readFileSync('pages/friend-requests/friend-requests.js', 'utf8')
const requestPageView = fs.readFileSync('pages/friend-requests/friend-requests.wxml', 'utf8')

assert(friendSource.includes("type: 'friend_request'"))
assert(friendSource.includes("type: 'friend_request_result'"))
assert(friendSource.includes('sendFriendRequestSubscribeMessage'))
assert(friendSource.includes('notifyFriendRequestResult'))
assert(friendSource.includes('cloud.openapi.subscribeMessage.send'))
assert(friendSource.includes('markFriendRequestNotificationRead'))
assert(friendConfig.permissions.openapi.includes('subscribeMessage.send'))
assert(notificationSource.includes("'friendRequest', 'orderCreated', 'orderStatus'"))
assert(popupSource.includes("friend_request: { icon: '👥'"))
assert(popupSource.includes("friend_request_result: { icon: '🤝'"))
assert(profileSource.includes('pendingFriendRequestCount'))
assert(profileSource.includes("action: 'getFriendRequests'"))
assert(profileView.includes('pendingFriendRequestCount > 0'))
assert(friendsView.includes('friendRequestCount > 0'))
assert(friendsView.includes('request-count-badge'))
assert(friendSource.includes("case 'cancelFriendRequest'"))
assert(friendSource.includes("case 'deleteFriendRequestRecord'"))
assert(friendSource.includes("case 'deleteReceivedFriendRequestRecord'"))
assert(friendSource.includes('senderDeletedAt'))
assert(friendSource.includes('receiverDeletedAt'))
assert(friendSource.includes('getSentRequestStatusMeta'))
assert(friendSource.includes('getReceivedRequestStatusMeta'))
assert(requestPageSource.includes('onCancelSentRequest'))
assert(requestPageSource.includes('onDeleteSentRequest'))
assert(requestPageSource.includes('onDeleteReceivedRequest'))
assert(requestPageSource.includes('displayedReceivedHistoryRequests'))
assert(requestPageSource.includes('displayedSentRequests'))
assert(requestPageSource.includes('toggleReceivedHistory'))
assert(requestPageSource.includes('toggleSentRequests'))
assert(requestPageView.includes('sent-swipe-row'))
assert(requestPageView.includes('取消绑定'))
assert(requestPageView.includes('已收到记录'))
assert(requestPageView.includes('展开全部记录'))

console.log('friend request notification: pass')
