const assert = require('assert')
const fs = require('fs')

const home = fs.readFileSync('pages/index/index.js', 'utf8')
const form = fs.readFileSync('pages/recipe-form/recipe-form.js', 'utf8')
const detail = fs.readFileSync('pages/recipe-detail/recipe-detail.js', 'utf8')
const recipeList = fs.readFileSync('pages/recipe-list/recipe-list.js', 'utf8')
const myRecipe = fs.readFileSync('pages/my-recipe/my-recipe.js', 'utf8')
const favorites = fs.readFileSync('pages/favorites/favorites.js', 'utf8')
const orderList = fs.readFileSync('pages/order-list/order-list.js', 'utf8')
const orderDetail = fs.readFileSync('pages/order-detail/order-detail.js', 'utf8')
const friends = fs.readFileSync('pages/friends/friends.js', 'utf8')
const friendRequests = fs.readFileSync('pages/friend-requests/friend-requests.js', 'utf8')

assert(home.includes('loadRecommendRecipes: function(silent = false)'))
assert(home.includes('if (!silent) this.setData({ loading: true })'))
assert(home.includes('this.loadRecommendRecipes(true)'))
assert(!home.includes("success: () => {\n        this._needsRecommendRefresh = true"))
assert(form.includes('this.markHomeRecommendRefresh()'))
assert(form.includes("previousPage.route === 'pages/index/index'"))
assert(home.includes('recipeDataVersion'))
assert(form.includes('app.globalData.recipeDataVersion = (app.globalData.recipeDataVersion || 0) + 1'))
assert(detail.includes('app.globalData.recipeDataVersion = (app.globalData.recipeDataVersion || 0) + 1'))
assert(recipeList.includes('this.refreshData(recipeDataChanged && !needsRefresh)'))
assert(recipeList.indexOf('const recipeDataChanged') > recipeList.indexOf('onShow: function ()'))
assert(myRecipe.includes('this.refreshData(true)'))
assert(favorites.includes('favoriteDataChanged'))
assert(orderList.includes('orderDataChanged'))
assert(orderDetail.includes('globalData.orderDataVersion'))
assert(friends.includes('friendDataChanged'))
assert(friendRequests.includes('globalData.friendDataVersion'))

console.log('home silent refresh: pass')
