const assert = require('assert')
const fs = require('fs')

const cloud = fs.readFileSync('cloudfunctions/notification/index.js', 'utf8')
const page = fs.readFileSync('pages/notifications/notifications.js', 'utf8')
const wxml = fs.readFileSync('pages/notifications/notifications.wxml', 'utf8')
const wxss = fs.readFileSync('pages/notifications/notifications.wxss', 'utf8')
const popup = fs.readFileSync('components/global-notification-popup/global-notification-popup.js', 'utf8')
const popupView = fs.readFileSync('components/global-notification-popup/global-notification-popup.wxml', 'utf8')

assert(cloud.includes("case 'delete'"))
assert(cloud.includes("case 'getWishUnreadCount'"))
assert(cloud.includes("case 'markWishRead'"))
assert(cloud.includes('excludeIds = []'))
assert(cloud.includes('!excluded.has(notification._id)'))
assert(cloud.includes("['wish_received', 'wish_share']"))
assert(cloud.includes("return '/pages/wish-list/wish-list?mode=pool'"))
assert(cloud.includes('normalizeWishTargetPage(item)'))
assert(!cloud.includes('mode=acceptWish&wishId=${wishId}'))
assert(cloud.includes('deleteNotification(openid, event.notificationId)'))
assert(cloud.includes("where({\n    recipientId: openid\n  }).update"))
assert(page.includes('onNotificationTouchStart'))
assert(page.includes('onDeleteNotification'))
assert(page.includes("action: 'delete'"))
assert(page.includes('read: item.read === true'))
assert(page.includes('wish_received'))
assert(page.includes('wish_status'))
assert(wxml.includes('notification-swipe-item'))
assert(wxml.includes('notification-delete-action'))
assert(wxml.includes('bindtouchmove="onNotificationTouchMove"'))
assert(wxss.includes('.notification-swipe-item'))
assert(wxss.includes('width: 76px;'))
assert(!wxss.includes('border: 1rpx solid rgba(232, 222, 216, 0.78);'))
assert(popup.includes("this.finish(false, 'later')"))
assert(popup.includes("this.finish(false, 'acknowledged')"))
assert(popupView.includes('bindtap="onClose"'))
assert(popupView.includes('bindtap="onAcknowledge">我知道了'))
assert(popupView.includes('bindtap="onLater">稍后再看'))

console.log('notifications: pass')
