const assert = require('assert')
const fs = require('fs')
const tagData = require('../utils/tagData')

const formPage = fs.readFileSync('pages/recipe-form/recipe-form.js', 'utf8')
const formView = fs.readFileSync('pages/recipe-form/recipe-form.wxml', 'utf8')
const formStyle = fs.readFileSync('pages/recipe-form/recipe-form.wxss', 'utf8')
const cropPage = fs.readFileSync('pages/image-crop/image-crop.js', 'utf8')
const cropView = fs.readFileSync('pages/image-crop/image-crop.wxml', 'utf8')
const detailView = fs.readFileSync('pages/recipe-detail/recipe-detail.wxml', 'utf8')
const detailStyle = fs.readFileSync('pages/recipe-detail/recipe-detail.wxss', 'utf8')
const recipeCloud = fs.readFileSync('cloudfunctions/recipe/index.js', 'utf8')

assert.deepStrictEqual(
  tagData.getPreparationTimes().map(item => Number(item.value)),
  [5, 10, 15, 20, 25, 30, 40, 50, 60, 120]
)
assert(formPage.includes('recipe_form_draft_${openid}'))
assert(formPage.includes("title: '继续上次填写？'"))
assert(formPage.includes('saveLocalDraft()'))
assert(formPage.includes('setCoverImage(e)'))
assert(formPage.includes('images.unshift(coverImage)'))
assert(formPage.includes('sideIngredients'))
assert(formPage.includes('seasonings'))
assert(!formPage.includes('第${i + 1}步还没写'))
assert(formView.includes('配料（可选）'))
assert(formView.includes('调料（可选）'))
assert(formView.includes('统一裁剪为 1:1'))
assert(formView.includes('class="cover-badge"'))
assert(formView.includes('catchtap="setCoverImage"'))
assert(formStyle.includes('height: 216rpx'))
assert(cropPage.includes('const cutHeight = cutWidth'))
assert(cropPage.includes('destHeight: 720'))
assert(cropView.includes('作为 1:1 菜谱图片'))
assert(detailStyle.includes('height: 750rpx'))
assert(detailView.includes('recipe.sideIngredients'))
assert(detailView.includes('recipe.seasonings'))
assert(recipeCloud.includes("sideIngredients: String(sideIngredients || '').trim()"))
assert(!recipeCloud.includes("message: '请添加制作步骤'"))

console.log('recipe form draft: pass')
