const assert = require('assert')
const fs = require('fs')

const cloud = fs.readFileSync('cloudfunctions/recipe/index.js', 'utf8')
const adminCloud = fs.readFileSync('cloudfunctions/admin/index.js', 'utf8')
const page = fs.readFileSync('pages/my-recipe/my-recipe.js', 'utf8')
const pageWxml = fs.readFileSync('pages/my-recipe/my-recipe.wxml', 'utf8')
const component = fs.readFileSync('components/recipe-item/recipe-item.js', 'utf8')
const componentWxml = fs.readFileSync('components/recipe-item/recipe-item.wxml', 'utf8')
const adminDataPage = fs.readFileSync('pages/admin-data/admin-data.js', 'utf8')
const adminDataWxml = fs.readFileSync('pages/admin-data/admin-data.wxml', 'utf8')
const rules = JSON.parse(fs.readFileSync('database.rules.json', 'utf8'))
const readme = fs.readFileSync('README.md', 'utf8')

assert(cloud.includes("case 'getViewers'"))
assert(cloud.includes("case 'getFavoriteUsers'"))
assert(cloud.includes('recordRecipeView(recipeId, openid)'))
assert(cloud.includes("collection('recipe_views')"))
assert(cloud.includes('requirePrimaryAdmin(openid)'))
assert(cloud.includes("orderBy('viewCount', 'desc').limit(20)"))
assert(cloud.includes("orderBy('createdAt', 'desc').limit(20)"))
assert(cloud.includes('getRecipeFavoriteUsers'))
assert(adminCloud.includes('isPrimaryAdmin: admin.openid === admin.primaryAdminOpenid'))
assert(component.includes('showViewerInfo'))
assert(component.includes("triggerEvent('viewerinfo'"))
assert(componentWxml.includes('catchtap="onViewerInfo"'))
assert(page.includes('isPrimaryAdmin'))
assert(page.includes('onViewerInfo: function'))
assert(pageWxml.includes('show-viewer-info="{{isPrimaryAdmin}}"'))
assert(pageWxml.includes('查看次数前 20 位用户'))
assert(pageWxml.includes('{{item.viewCount}} 次'))
assert(adminDataPage.includes('onRecipeAudienceTap'))
assert(adminDataWxml.includes('data-type="viewers"'))
assert(adminDataWxml.includes('data-type="favorites"'))
assert(adminDataWxml.includes('查看次数前 20 位用户'))
assert(adminDataWxml.includes('showAudienceModal'))
assert.deepStrictEqual(rules.recipe_views, { read: false, write: false })
assert(readme.includes('recipe_views'))

console.log('recipe viewers: pass')
