const assert = require('assert')
const fs = require('fs')

const cloud = fs.readFileSync('cloudfunctions/recipe/index.js', 'utf8')
const page = fs.readFileSync('pages/recipe-detail/recipe-detail.js', 'utf8')
const wxml = fs.readFileSync('pages/recipe-detail/recipe-detail.wxml', 'utf8')
const rules = JSON.parse(fs.readFileSync('database.rules.json', 'utf8'))

assert(cloud.includes("case 'saveInteraction'"))
assert(cloud.includes('recipe_interactions'))
assert(cloud.includes('getRecipeInteractionSummary'))
assert(cloud.includes('normalizeInteractionReactions'))
assert(cloud.includes('recipe.myInteractions = interaction.myReactions'))
assert(cloud.includes('reactions: nextReactions'))
assert(cloud.includes('reactions.includes(reaction)'))
assert(cloud.includes('normalizeInteractionReactions(item)'))
assert(page.includes('onInteractionTap'))
assert(page.includes('getInteractionOptions'))
assert(page.includes("'recipe.myInteractions': myInteractions"))
assert(wxml.includes('interactionOptions'))
assert(wxml.includes("item.selected ? 'active' : ''"))
assert.deepStrictEqual(rules.recipe_interactions, { read: false, write: false })

console.log('recipe interactions: pass')
